name: Run Unit Tests
on:
  push:
    branches:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y xz-utils curl

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Verify Nix installation
        run: nix --version

      - name: Devshell to flake.nix for dependencies
        run: nix develop

      - name: Build the project
        run: nix develop --command make

      - name: Run executables
        run: ./my_nm --help && ./my_objdump --help

      - name: Build unit-tests
        run: nix develop --command make tests_run

      - name: Fclean all
        run: nix develop --command make fclean
